#Use root/example as user/password credentials
version: '3.1'

# x-common-variables: &common-variables
#   REACT_APP_SERVER_PORT: 8000
#   REACT_APP_SERVER_URL: 

services:

  react:
    image: react
    build: 
      context: .
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_PORT=8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - server
    command: npm start